/* tslint:disable */
/* eslint-disable */
/**
 * Stripe Payment Sample
 * this is an stripe payment example
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev@mattiamueggler.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

